// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"go-web-example/views/components"
)

func Base() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>GO-WEB-EXAMPLE</title><link rel=\"stylesheet\" href=\"/css/index.css\"><link href=\"https://cdn.jsdelivr.net/npm/daisyui@4.10.5/dist/full.min.css\" rel=\"stylesheet\" type=\"text/css\"><script src=\"https://cdn.tailwindcss.com\"></script><html data-theme=\"light\"></html></head><body><header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Navigation().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<footer><footer class=\"footer p-10 bg-base-200 text-base-content\"><nav><h6 class=\"footer-title\">Services</h6><a class=\"link link-hover\">Branding</a> <a class=\"link link-hover\">Design</a> <a class=\"link link-hover\">Marketing</a> <a class=\"link link-hover\">Advertisement</a></nav><nav><h6 class=\"footer-title\">Company</h6><a class=\"link link-hover\">About us</a> <a class=\"link link-hover\">Contact</a> <a class=\"link link-hover\">Jobs</a> <a class=\"link link-hover\">Press kit</a></nav><nav><h6 class=\"footer-title\">Legal</h6><a class=\"link link-hover\">Terms of use</a> <a class=\"link link-hover\">Privacy policy</a> <a class=\"link link-hover\">Cookie policy</a></nav><form><h6 class=\"footer-title\">Newsletter</h6><fieldset class=\"form-control w-80\"><label class=\"label\"><span class=\"label-text\">Enter your email address</span></label><div class=\"join\"><input type=\"text\" placeholder=\"username@site.com\" class=\"input input-bordered join-item\"> <button class=\"btn btn-primary join-item\">Subscribe</button></div></fieldset></form></footer></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
